-- MySQL Script generated by MySQL Workbench
-- Modified to include CASCADE DELETE
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema polideportivo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `polideportivo` ;
CREATE SCHEMA IF NOT EXISTS `polideportivo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `polideportivo` ;

-- -----------------------------------------------------
-- Table `polideportivo`.`deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`deportes` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`deportes` (
  `deporte_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`deporte_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`empleados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`empleados` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`empleados` (
  `empleado_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(9) NOT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(100) NULL DEFAULT NULL,
  `puesto` VARCHAR(50) NULL DEFAULT NULL,
  `fecha_contratacion` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`empleado_id`),
  UNIQUE INDEX `dni` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`instalaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`instalaciones` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`instalaciones` (
  `instalacion_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `capacidad` INT NULL DEFAULT NULL,
  `precio_hora` DECIMAL(10,2) NOT NULL,
  `estado` ENUM('disponible', 'mantenimiento', 'reservada') NULL DEFAULT 'disponible',
  PRIMARY KEY (`instalacion_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`clases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`clases` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`clases` (
  `clase_id` INT NOT NULL AUTO_INCREMENT,
  `deporte_id` INT NOT NULL,
  `empleado_id` INT NOT NULL,
  `instalacion_id` INT NOT NULL,
  `nombre` VARCHAR(100) NULL DEFAULT NULL,
  `nivel` VARCHAR(50) NULL DEFAULT NULL,
  `capacidad_maxima` INT NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NULL DEFAULT NULL,
  `dia_semana` ENUM('Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado', 'Domingo') NULL DEFAULT NULL,
  `hora_inicio` TIME NULL DEFAULT NULL,
  `hora_fin` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`clase_id`),
  INDEX `deporte_id` (`deporte_id` ASC) VISIBLE,
  INDEX `empleado_id` (`empleado_id` ASC) VISIBLE,
  INDEX `instalacion_id` (`instalacion_id` ASC) VISIBLE,
  INDEX `idx_clases_horario` (`dia_semana` ASC, `hora_inicio` ASC) VISIBLE,
  CONSTRAINT `clases_ibfk_1`
    FOREIGN KEY (`deporte_id`)
    REFERENCES `polideportivo`.`deportes` (`deporte_id`)
    ON DELETE CASCADE,
  CONSTRAINT `clases_ibfk_2`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `polideportivo`.`empleados` (`empleado_id`)
    ON DELETE CASCADE,
  CONSTRAINT `clases_ibfk_3`
    FOREIGN KEY (`instalacion_id`)
    REFERENCES `polideportivo`.`instalaciones` (`instalacion_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`clientes` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`clientes` (
  `cliente_id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(80) NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `direccion` VARCHAR(255) NULL,
  `fecha_registro` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `roles` ENUM("CLIENTE", "ADMIN") NULL DEFAULT 'CLIENTE',
  PRIMARY KEY (`cliente_id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`empleados_deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`empleados_deportes` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`empleados_deportes` (
  `empleado_id` INT NOT NULL,
  `deporte_id` INT NOT NULL,
  `nivel_certificacion` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`empleado_id`, `deporte_id`),
  INDEX `deporte_id` (`deporte_id` ASC) VISIBLE,
  CONSTRAINT `empleados_deportes_ibfk_1`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `polideportivo`.`empleados` (`empleado_id`)
    ON DELETE CASCADE,
  CONSTRAINT `empleados_deportes_ibfk_2`
    FOREIGN KEY (`deporte_id`)
    REFERENCES `polideportivo`.`deportes` (`deporte_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`gastos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`gastos` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`gastos` (
  `gasto_id` INT NOT NULL AUTO_INCREMENT,
  `concepto` VARCHAR(200) NOT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `fecha` DATE NOT NULL,
  `tipo` ENUM('mantenimiento', 'servicios', 'personal', 'otros') NULL DEFAULT NULL,
  `instalacion_id` INT NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`gasto_id`),
  INDEX `instalacion_id` (`instalacion_id` ASC) VISIBLE,
  INDEX `idx_gastos_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `gastos_ibfk_1`
    FOREIGN KEY (`instalacion_id`)
    REFERENCES `polideportivo`.`instalaciones` (`instalacion_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`inscripciones_clases`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`inscripciones_clases` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`inscripciones_clases` (
  `inscripcion_id` INT NOT NULL AUTO_INCREMENT,
  `clase_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `fecha_inscripcion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('activa', 'cancelada', 'completada') NULL DEFAULT 'activa',
  PRIMARY KEY (`inscripcion_id`),
  INDEX `clase_id` (`clase_id` ASC) VISIBLE,
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `inscripciones_clases_ibfk_1`
    FOREIGN KEY (`clase_id`)
    REFERENCES `polideportivo`.`clases` (`clase_id`)
    ON DELETE CASCADE,
  CONSTRAINT `inscripciones_clases_ibfk_2`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `polideportivo`.`clientes` (`cliente_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`instalaciones_deportes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`instalaciones_deportes` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`instalaciones_deportes` (
  `instalacion_id` INT NOT NULL,
  `deporte_id` INT NOT NULL,
  PRIMARY KEY (`instalacion_id`, `deporte_id`),
  INDEX `deporte_id` (`deporte_id` ASC) VISIBLE,
  CONSTRAINT `instalaciones_deportes_ibfk_1`
    FOREIGN KEY (`instalacion_id`)
    REFERENCES `polideportivo`.`instalaciones` (`instalacion_id`)
    ON DELETE CASCADE,
  CONSTRAINT `instalaciones_deportes_ibfk_2`
    FOREIGN KEY (`deporte_id`)
    REFERENCES `polideportivo`.`deportes` (`deporte_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`reservas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`reservas` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`reservas` (
  `reserva_id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `instalacion_id` INT NOT NULL,
  `deporte_id` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  `estado` ENUM('pendiente', 'confirmada', 'cancelada') NULL DEFAULT 'pendiente',
  `precio_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`reserva_id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `instalacion_id` (`instalacion_id` ASC) VISIBLE,
  INDEX `deporte_id` (`deporte_id` ASC) VISIBLE,
  INDEX `idx_reservas_fecha` (`fecha` ASC) VISIBLE,
  CONSTRAINT `reservas_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `polideportivo`.`clientes` (`cliente_id`)
    ON DELETE CASCADE,
  CONSTRAINT `reservas_ibfk_2`
    FOREIGN KEY (`instalacion_id`)
    REFERENCES `polideportivo`.`instalaciones` (`instalacion_id`)
    ON DELETE CASCADE,
  CONSTRAINT `reservas_ibfk_3`
    FOREIGN KEY (`deporte_id`)
    REFERENCES `polideportivo`.`deportes` (`deporte_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `polideportivo`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `polideportivo`.`pagos` ;
CREATE TABLE IF NOT EXISTS `polideportivo`.`pagos` (
  `pago_id` INT NOT NULL AUTO_INCREMENT,
  `reserva_id` INT NOT NULL,
  `fecha_pago` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `monto` DECIMAL(10,2) NOT NULL,
  `metodo_pago` ENUM('efectivo', 'tarjeta', 'transferencia') NULL DEFAULT NULL,
  PRIMARY KEY (`pago_id`),
  INDEX `reserva_id` (`reserva_id` ASC) VISIBLE,
  INDEX `idx_pagos_fecha` (`fecha_pago` ASC) VISIBLE,
  CONSTRAINT `pagos_ibfk_1`
    FOREIGN KEY (`reserva_id`)
    REFERENCES `polideportivo`.`reservas` (`reserva_id`)
    ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;